FROM elasticsearch:7.17.0

RUN elasticsearch-plugin install analysis-icu 
RUN elasticsearch-plugin install analysis-kuromoji 
RUN elasticsearch-plugin install analysis-smartcn 
RUN elasticsearch-plugin install analysis-stempel
